# Generated by Django 3.2.10 on 2021-12-30 08:30

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField()),
                ('is_ngo_user', models.BooleanField(default=False)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FundRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('document', models.FileField(upload_to='documents/')),
                ('verification_status', models.BooleanField(null=True)),
                ('current_user', models.CharField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(blank=True, max_length=30)),
                ('head_of_ngo', models.CharField(blank=True, max_length=30)),
                ('contactNo', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('registration_cerificate_Trust_Society', models.FileField(blank=True, upload_to='verification')),
                ('certificate_12A', models.FileField(blank=True, upload_to='verification')),
                ('beneficiary_profiles', models.FileField(blank=True, upload_to='verification')),
                ('verification_status', models.BooleanField(blank=True, default=None, null=True)),
                ('ngo_current_user', models.CharField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, max_length=40)),
            ],
        ),
    ]
