# Generated by Django 3.0.5 on 2022-01-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20211230_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequestmodel',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='ngo_current_user',
        ),
    ]
