# Generated by Django 3.2.10 on 2022-01-03 05:40

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20220103_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequestmodel',
            name='request_id',
            field=models.CharField(default=django_currentuser.middleware.get_current_authenticated_user, max_length=20),
        ),
    ]
