# Generated by Django 3.2.10 on 2022-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_donorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
