# Generated by Django 3.2.10 on 2022-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20220227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='current_user',
            field=models.BigIntegerField(blank=True),
        ),
    ]
