# Generated by Django 3.2.10 on 2022-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_alter_donorlist_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='donated_to',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
