# Generated by Django 3.2.12 on 2022-03-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0014_donorlist_donated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequestmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.fundrequestmodel')),
            ],
        ),
    ]
