# Generated by Django 3.2.12 on 2022-03-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0015_auto_20220308_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequestmodel',
            name='image',
        ),
    ]
