# Generated by Django 3.2.12 on 2022-03-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_auto_20220308_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleimage',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charity.fundrequestmodel'),
            preserve_default=False,
        ),
    ]
