# Generated by Django 3.2.12 on 2022-03-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0019_alter_multipleimage_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.fundrequestmodel'),
        ),
    ]
