# Generated by Django 3.2.10 on 2022-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0020_alter_multipleimage_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequestmodel',
            name='amount_recieved',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundrequestmodel',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
