# Generated by Django 3.2.10 on 2022-03-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0022_alter_fundrequestmodel_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequestmodel',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
