# Generated by Django 3.2.10 on 2022-03-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0024_auto_20220319_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleimage',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='multipleimage',
            name='image4',
        ),
    ]
