# Generated by Django 3.2.10 on 2022-03-21 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0026_fundrequestmodel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequestmodel',
            name='postted_at',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
