# Generated by Django 3.2.10 on 2022-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0027_fundrequestmodel_postted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequestmodel',
            name='verification_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
