# Generated by Django 3.2.10 on 2022-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0028_alter_fundrequestmodel_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequestmodel',
            name='verification_status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
