# Generated by Django 3.2.10 on 2022-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0029_alter_fundrequestmodel_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review_message', models.CharField(max_length=1000)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='testimonials_pic/')),
                ('donated_to', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
