# Generated by Django 3.2.10 on 2022-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0030_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='verification_status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
