# Generated by Django 3.0.5 on 2021-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_ngo',
            field=models.BooleanField(default=False),
        ),
    ]
