# Generated by Django 3.0.5 on 2021-12-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newuser_is_ngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
    ]
